# Generated by Django 4.2.5 on 2023-10-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reservas', models.DateField(verbose_name='fecha_reservas')),
                ('fecha_salida', models.DateField(verbose_name='fecha_salida')),
                ('cant_personas', models.IntegerField(verbose_name='cant_personas')),
                ('mensaje', models.CharField(max_length=150, null=True, verbose_name='mensaje')),
            ],
        ),
    ]
