# Generated by Django 4.2.5 on 2023-10-30 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='desayuno',
            field=models.BooleanField(default=False, verbose_name='Desayuno:'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='fecha_reserva',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hotel',
            name='numero_reserva',
            field=models.IntegerField(default=723184),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='estrellas',
            field=models.IntegerField(verbose_name='Estrellas:'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre:'),
        ),
    ]
