# Generated by Django 4.2.7 on 2023-11-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='numero_reserva',
            field=models.IntegerField(default=705434),
        ),
    ]
